### PR TITLE
Documentation amendments for Scopes Build feature

### PR DESCRIPTION
**Pull request by wpopielarski**

### CODE REVIEW

**Comment by sschaef** [comment]
I already cleaned it up. I think you reverted most of the changes with this PR.

**Comment by wpopielarski** [comment]
I just put there 'a' and 'the' articles mainly, added some grammar changes
in sentences (to make them clearer) and made clickable pictures. And I
think that in places where you cleaned the text your changes are retained.
Anyway thanks for your merge and if something is wrong it wasn't my
intention.


2015-05-13 0:24 GMT+02:00 Simon Schäfer <notifications@github.com>:

**Comment by sschaef** [comment]
There are a few articles that improve the text, but most changes are unwanted. They seem to come from some merge errors you had. Please have another look.

**Comment by wpopielarski** [comment]
ok

2015-05-18 9:56 GMT+02:00 Simon Schäfer <notifications@github.com>:

**Comment by sschaef** [comment]
outdated work

**Pull request closed without merging**
