### PR TITLE
Update docs after removing an option to close SPCs with open editors

### PR DESCRIPTION
**Pull request by mpociecha**
The checkbox has been removed so this commit provides the new
screenshot and also the description in Memory consumption section is
updated.

### CODE REVIEW

**Comment by mpociecha** [comment]
It's related to https://github.com/scala-ide/scala-ide/pull/901

**Comment by sschaef** [comment]
LGTM

**Comment by mpociecha** [comment]
@sschaef I removed also "or start typing in an existing file". Right now editors have to be closed and hence it's not possible to start typing in the existing one. I overlooked this previously.

**Comment by mpociecha** [comment]
What about this PR?

**Pull request merged**
